# Generated by Django 5.0.6 on 2024-08-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_upload',
            field=models.FileField(default='e-book/default_book.jpg', upload_to='e-book/'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='cover/default_cover.jpg', upload_to='cover/'),
        ),
    ]
