# Generated by Django 5.0.6 on 2024-08-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_book_book_upload_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='images/'),
        ),
    ]
