# Generated by Django 5.0.6 on 2024-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_member_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='book_cover/default_cover.jpg', upload_to='book_cover/'),
        ),
    ]
