# Generated by Django 5.0.6 on 2024-08-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_author_remove_book_publisher_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
