# Generated by Django 5.0.6 on 2024-09-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_book_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
    ]
