# Generated by Django 5.0.6 on 2024-09-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_book_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
