# Generated by Django 5.0.6 on 2024-10-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_payment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='book_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
