# Generated by Django 5.0.6 on 2025-02-19 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
