# Generated by Django 5.0.6 on 2025-02-20 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_borrowing_approved_borrowing_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
