# Generated by Django 5.0.6 on 2025-02-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_borrowing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='due_date',
        ),
    ]
