# Generated by Django 5.0.6 on 2025-02-20 10:45

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_borrowing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(blank=True, default=home.models.expiry, null=True),
        ),
    ]
