# Generated by Django 5.0.6 on 2025-02-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_borrowing_due_date'),
    ]

    operations = [
    ]
