# Generated by Django 5.0.6 on 2025-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_fine_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
