# Generated by Django 5.0.6 on 2025-03-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_payment_purchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
