# Generated by Django 5.0.6 on 2025-04-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_reservation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='title',
            new_name='book_title',
        ),
    ]
