# Generated by Django 5.0.6 on 2025-04-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='fine_amount',
        ),
    ]
