# Generated by Django 5.0.6 on 2025-04-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_borrowing_fine_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
