# Generated by Django 5.0.6 on 2025-04-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_delete_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing_details',
            name='days_overdue',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
