# Generated by Django 5.0.6 on 2025-04-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_borrowing_details_days_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing_details',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
    ]
