# Generated by Django 5.0.6 on 2025-04-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_borrowing_details_fine_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine_payment',
            name='borrow_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.borrowing_details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchased_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
