# Generated by Django 5.0.6 on 2025-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_fine_payment_borrow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine_payment',
            name='borrow_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
