# Generated by Django 5.0.6 on 2025-04-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_fine_payment_borrow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine_payment',
            name='borrow_id',
        ),
    ]
